### PR TITLE
 Add regression test of densest star field

### LINKED ISSUE #124: Add full catalog regression test with a dense field
This is an action in #120

### PR DESCRIPTION
**Pull request by taldcroft**
This is based off of col-spoilers branch because that is likely to impact results.

Closes #124

### CODE REVIEW

**Comment by jeanconn** [comment]
Does this just need rebase?

**Comment by taldcroft** [comment]
@jeanconn - I have no idea what happened, but can you clean this up (rebase after fixing up and merging #149)?

**Comment by jeanconn** [comment]
Yep, got this.

**Comment by taldcroft** [comment]
Unless maybe #146 introduced this conflict?

**Comment by jeanconn** [comment]
Yes, that conflict was expected. I thought this needed rebase just because it is difficult to review when it already had the col-spoil branch commits too.

**Pull request merged**
