### PR TITLE
Get ACA penalty and planning limits from chandra_models

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

This gets the ACA penalty and planning limits from chandra_models. It uses the module-level `__getattr__` to make these characteristics be lazily defined to prevent import-time issues.

The current code has been tested using a local version of chandra_models in the SKA data that has a tagged "release" from https://github.com/sot/chandra_models/pull/74 as the default model version. Ideally we should get a new version of chandra_models 3.35.1 promoted that includes only the ACA model update.

## Testing

- [x] Passes unit tests on MacOS
- [ ] Functional testing

### CODE REVIEW

**Comment by jeanconn** [comment]
Regarding "The current code is using a local version of chandra_models that has a tagged "release" from sot/chandra_models#74 as the default model version.", do you just mean that in your testing you have a SKA set with a nonstandard version of chandra_models?  Or is there something in the code that I'm missing?

**Comment by taldcroft** [comment]
> do you just mean that in your testing you have a SKA set with a nonstandard version of chandra_models? 

No, I changed my local "flight" Ska data version of chandra_models for testing purposes. Since (1) chandra_models is not currently used in any flight tools, and (2) the change is innocuous anyway, I was not concerned about this. My local mod will get wiped out the next time I do a ska_sync.

**Comment by jeanconn** [comment]
I'm not sure how that is a "no"?

**Comment by taldcroft** [comment]
I interpreted a "SKA set" to mean changing my SKA env var to a different value where the test Ska data were located.

**Comment by jeanconn** [comment]
Gotcha.  Your SKA is set to a directory that has a nonstandard chandra_models was my point.  Though in your strategy you just used the one that you generally use.  Either way, there's nothing funny in the current PR/code to pick up a different version, it is just the test environment.

**Review by jeanconn — APPROVED** [review]
I like this implementation.  Though now that we have a good use case of get_xija_model_spec I'm wondering about the easiest way to specify a nonstandard location of the chandra_models repo for testing.  Env vars are annoying but maybe it is worth one?

**Pull request merged**
