### PR TITLE
Fid and acq concurrent optimization

### LINKED ISSUE #43: fid selection
Fid selection in the context of proseco requires a little care to maintain speed without sacrificing acquisition margin and science quality.  Sub-tasks (which will break out to issues / PRs)

- [x] Define algorithm, document and present to SSAWG
- [x] Implement basic support code (e.g. get the position of a fid light on ACA CCD).  Use Matlab tools code as the basis for continuity with exiting positions in load products.
- [x] Test support code against flight catalogs.
- [x] Implement algorithm and test.  Current idea is tightly integrated with acq star selection.
  - [x] First part: core code and initial fid catalog selection #49 
  - [x] Integrated fid and acq optimization #59

### PR DESCRIPTION
**Pull request by taldcroft**
Optimize fid and acquisition catalogs concurrently.

Closes #43.

### CODE REVIEW

**Comment by taldcroft** [comment]
The intent is probably to remove and rebase-away the aca.py file, but it gives @jeanconn an idea where I'm going.

**Comment by jeanconn** [comment]
For overall interface, were you thinking you'd use the get_acq_fid_.. function on ORs and the get_acq... function on its own for ERs?

**Comment by taldcroft** [comment]
I was thinking about one function for everything.

**Comment by taldcroft** [comment]
Superceded by #96.

**Pull request closed without merging**
