### PR TITLE
WIP: Add a force_catalog keyword arg for analysis

### PR DESCRIPTION
**Pull request by jeanconn**
Add a force_catalog keyword arg for analysis

### CODE REVIEW

**Comment by jeanconn** [comment]
This has been hanging around and needs at least a test.

**Comment by taldcroft** [comment]
I'd rather not put this in the API for this rarely-used option.  Note that in addition to a test you would need to update all the docs that reference available keywords.

I'd suggest instead to add a function to `core.py` : `includes_from_obsid(obsid)` that returns a dict so that you can do:
```
from proseco.core import includes_from_obsid
get_aca_catalog(obsid, **includes_from_obsid(obsid))
```

**Comment by jeanconn** [comment]
I was thinking that get_aca_catalog(obsid, force_catalog=True) might be more useful than get_aca_catalog(obsid) at this point.

**Comment by taldcroft** [comment]
What are the use cases for that?  I think all the existing unit tests that reference `obsid` are correct as written, and in the recent case for SEP0919 prelim I did not see a need to look at the force-catalog version of the 3 reports you supplied.

**Comment by jeanconn** [comment]
I wasn't suggesting changing the default (which would apply to the "I think all the existing unit tests that reference obsid are correct as written").  I was much more interested in updating the acq stats database (or a new table) to have the last 5 years of proseco P2 values and acq probs for individual stars to do something like https://github.com/sot/starcheck/pull/257#discussion_r224481777 .

Which is, of course, fine with the helper function idea you suggest.  My point was just that I am *also* not using get_aca_catalog(obsid) much at this point, though of course we may want to do so for large recalibration efforts.

**Comment by taldcroft** [comment]
Good points, but not a driver for an API change in my view.

**Comment by jeanconn** [comment]
Closing this in favor of #311

**Pull request closed without merging**
