### PR TITLE
Use proseco_agasc_1p7 for star selection

### PR DESCRIPTION
**Pull request by taldcroft**
Changes to support using an AGASC that is optimized for proseco.

See also https://github.com/sot/agasc/pull/38.

### CODE REVIEW

**Comment by taldcroft** [comment]
Sorry, lost track of this one since I had planned for it to be in 4.2.  Was hoping to get functional testing in MATLAB sooner rather than later.

I just rebased and it is passing tests on Mac.  From my perspective this is good for merge.

**Comment by jeanconn** [comment]
This looks fine to me.  Does it need any additional tests?

**Comment by jeanconn** [comment]
I'm guessing you can't cut RSV3 if you want to use it later to update mag error in agasc 4.7 update_color1_column .

**Comment by taldcroft** [comment]
So there is a new proseco_agasc_1p7 generated by a new agasc package.  But neither of these require a new ska release.  Mark's tools will auto resync that agasc file.

**Comment by jeanconn** [comment]
I don't know how that comment applies.

**Comment by jeanconn** [comment]
I assume that when we promote proseco on matlab, that we'll have agasc 4.7 in place in that ska3, so proseco 4.3 should be compatible with the agasc 4.7 module.

**Comment by taldcroft** [comment]
I put rsv3 back n the file so problem goes away.

**Comment by jeanconn** [comment]
OK,  now I'm on the same page (your comment above with "So there is a new" made it sound like you were explaining what this PR is supposed to do... not that you'd just made a new file put back rsv3).  I can rerun these tests on HEAD once that file is in SKA/data/agasc.

**Comment by taldcroft** [comment]
Passing tests on HEAD and GRETA (ska3-flight 2018.12.06-2ed05de), so merging.

For the record:
```
SOT@chimchim% ls -lrt
total 5398020
-rw-rw-r-- 1 SOT pegasus 1149858665 May 19  2013 miniagasc_1p6.h5
-rw-rw-r-- 1 SOT pegasus  133131728 Aug  8  2014 ra_dec.npy
-rw-r--r-- 1 SOT pegasus 2580353411 Sep 24 18:38 agasc1p7.h5
-rw-r--r-- 1 SOT pegasus 1140687415 Sep 24 18:39 miniagasc_1p7.h5
lrwxrwxrwx 1 SOT pegasus         16 Sep 24 21:13 miniagasc.h5 -> miniagasc_1p7.h5
-rw-rw-r-- 1 SOT pegasus  518103199 Dec  9 15:57 proseco_agasc_1p7.h5

SOT@chimchim% md5sum proseco_agasc_1p7.h5
4972f0257bceaded7221dfef9ff70f83  proseco_agasc_1p7.h5
```

**Comment by jeanconn** [comment]
With this merged, is 4.3 ready-to-go?

**Pull request merged**
